fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: forbid-new-submodules
  - id: detect-private-key
  - id: no-commit-to-branch
    args: ["--branch", "master"]

- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
  - id: nbstripout

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.10
  hooks:
  - id: bandit
    args: [
      "-c", "./src/pyproject.toml",
      "src"
    ]
    additional_dependencies: [ "bandit[toml]" ]
    always_run: true
    verbose: true

- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    args: [
      "--config", "./src/pyproject.toml",
      "src"
    ]
    additional_dependencies: [ "black[toml]" ]
    always_run: true
    verbose: true

- repo: https://github.com/pylint-dev/pylint
  rev: v3.3.1
  hooks:
  - id: pylint
    args: ["--rcfile", "./.pylintrc", "src"]
    always_run: true
    verbose: true

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [
      "--profile", "black",
      "--settings-path", "./src/pyproject.toml",
      "src"
    ]
    additional_dependencies: [ "isort[toml]" ]
    always_run: true
    verbose: true

- repo: https://github.com/rubik/xenon
  rev: v0.9.0
  hooks:
  - id: xenon
    args: [
      "--max-absolute=B",
      "--max-modules=B",
      "--max-average=A",
      "--exclude=*test_*",
      "src"
    ]
    always_run: true
    verbose: true

- repo: local
  hooks:
  - id: mypy
    name: mypy
    entry: mypy src
    args: [
      "--show-error-codes",
      "--config-file",
      "./src/pyproject.toml"
    ]
    language: python
    types: [python]
    pass_filenames: false
    always_run: true
    verbose: true

- repo: https://github.com/python-poetry/poetry
  rev: 1.8.4
  hooks:
  - id: poetry-check
    args: ["-C", "./src"]
    always_run: true
    verbose: true
  - id: poetry-lock
    args: ["-C", "./src"]
  - id: poetry-export
    args: [
      "-C", "./src",
      "-f", "requirements.txt",
      "-o", "./src/requirements.txt",
      "--without-hashes"
    ]
    always_run: true
    verbose: true
  - id: poetry-install
    args: ["-C", "./src"]
    always_run: true
    verbose: true
